version: '3.7'

services:
  management_db:
    container_name: management_db
    image: postgres:13
    networks:
      - management
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - .data/pgdata:/var/lib/postgresql/data
  cache_db:
    container_name: cache_db
    image: redis:7.0.4-alpine
    networks:
      - management
    env_file:
      - .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - .data/cache:/data
networks:
  management:
